2024-12-09 18:47:30,621 INFO:  * Restarting with stat [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:47:32,021 INFO: Flask application started successfully. [in /Users/lq991027/urban_lab_project/app.py:46]
2024-12-09 18:47:32,290 WARNING:  * Debugger is active! [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:47:32,330 INFO:  * Debugger PIN: 140-908-366 [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:49:00,635 INFO: 127.0.0.1 - - [09/Dec/2024 18:49:00] "GET /dashboard HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:49:00,717 INFO: 127.0.0.1 - - [09/Dec/2024 18:49:00] "GET /api/stats HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:51:52,421 INFO:  * Detected change in '/Users/lq991027/urban_lab_project/app.py', reloading [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:51:52,577 INFO:  * Restarting with stat [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:51:53,304 INFO: Flask application started successfully. [in /Users/lq991027/urban_lab_project/app.py:46]
2024-12-09 18:51:53,397 WARNING:  * Debugger is active! [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:51:53,459 INFO:  * Debugger PIN: 140-908-366 [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:52:14,708 INFO: 127.0.0.1 - - [09/Dec/2024 18:52:14] "GET /dashboard HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:52:14,779 INFO: 127.0.0.1 - - [09/Dec/2024 18:52:14] "GET /api/stats HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:52:16,053 ERROR: Error exporting CSV: (1146, "Table 'urban_lab_db.yourtable' doesn't exist") [in /Users/lq991027/urban_lab_project/app.py:124]
2024-12-09 18:52:16,053 ERROR: Error exporting CSV: (1146, "Table 'urban_lab_db.yourtable' doesn't exist") [in /Users/lq991027/urban_lab_project/app.py:124]
2024-12-09 18:52:16,054 INFO: 127.0.0.1 - - [09/Dec/2024 18:52:16] "[35m[1mGET /api/export HTTP/1.1[0m" 500 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:54:22,624 INFO:  * Detected change in '/Users/lq991027/urban_lab_project/app.py', reloading [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:54:22,694 INFO:  * Restarting with stat [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:54:23,766 INFO: Flask application started successfully. [in /Users/lq991027/urban_lab_project/app.py:46]
2024-12-09 18:54:23,901 WARNING:  * Debugger is active! [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:54:23,945 INFO:  * Debugger PIN: 140-908-366 [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:54:31,941 ERROR: Error exporting CSV: (1054, "Unknown column 'column1' in 'field list'") [in /Users/lq991027/urban_lab_project/app.py:124]
2024-12-09 18:54:31,941 ERROR: Error exporting CSV: (1054, "Unknown column 'column1' in 'field list'") [in /Users/lq991027/urban_lab_project/app.py:124]
2024-12-09 18:54:31,942 INFO: 127.0.0.1 - - [09/Dec/2024 18:54:31] "[35m[1mGET /api/export HTTP/1.1[0m" 500 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:58:07,142 INFO:  * Detected change in '/Users/lq991027/urban_lab_project/app.py', reloading [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:58:07,232 INFO:  * Restarting with stat [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:58:08,234 INFO: Flask application started successfully. [in /Users/lq991027/urban_lab_project/app.py:46]
2024-12-09 18:58:08,340 WARNING:  * Debugger is active! [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:58:08,359 INFO:  * Debugger PIN: 140-908-366 [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:58:12,718 INFO: 127.0.0.1 - - [09/Dec/2024 18:58:12] "GET /dashboard HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:58:12,792 INFO: 127.0.0.1 - - [09/Dec/2024 18:58:12] "GET /api/stats HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:58:15,794 ERROR: Error exporting table interactions: name 'make_response' is not defined [in /Users/lq991027/urban_lab_project/app.py:141]
2024-12-09 18:58:15,794 ERROR: Error exporting table interactions: name 'make_response' is not defined [in /Users/lq991027/urban_lab_project/app.py:141]
2024-12-09 18:58:15,797 INFO: 127.0.0.1 - - [09/Dec/2024 18:58:15] "[35m[1mGET /api/export?table=interactions HTTP/1.1[0m" 500 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:59:38,580 INFO:  * Detected change in '/Users/lq991027/urban_lab_project/app.py', reloading [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:59:38,642 INFO:  * Restarting with stat [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:59:39,536 INFO: Flask application started successfully. [in /Users/lq991027/urban_lab_project/app.py:46]
2024-12-09 18:59:39,636 WARNING:  * Debugger is active! [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:59:39,660 INFO:  * Debugger PIN: 140-908-366 [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:59:48,858 INFO: 127.0.0.1 - - [09/Dec/2024 18:59:48] "GET /dashboard HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:59:48,907 INFO: 127.0.0.1 - - [09/Dec/2024 18:59:48] "GET /api/stats HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 18:59:50,080 INFO: 127.0.0.1 - - [09/Dec/2024 18:59:50] "GET /api/export?table=events HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:04:20,587 INFO: 127.0.0.1 - - [09/Dec/2024 19:04:20] "GET /api/export?table=interactions HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:04:24,435 INFO: 127.0.0.1 - - [09/Dec/2024 19:04:24] "GET /api/export?table=interactions HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:12,519 INFO: Flask application started successfully. [in /Users/lq991027/urban_lab_project/app.py:46]
2024-12-09 19:46:12,620 INFO: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:12,620 INFO: [33mPress CTRL+C to quit[0m [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:12,623 INFO:  * Restarting with stat [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:12,937 INFO: Flask application started successfully. [in /Users/lq991027/urban_lab_project/app.py:46]
2024-12-09 19:46:13,002 WARNING:  * Debugger is active! [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:13,016 INFO:  * Debugger PIN: 140-908-366 [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:17,474 INFO: 127.0.0.1 - - [09/Dec/2024 19:46:17] "GET /dashboard HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:17,557 INFO: 127.0.0.1 - - [09/Dec/2024 19:46:17] "GET /api/stats HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:18,527 INFO: 127.0.0.1 - - [09/Dec/2024 19:46:18] "GET /dashboard HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:18,603 INFO: 127.0.0.1 - - [09/Dec/2024 19:46:18] "GET /api/stats HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:21,376 INFO: 127.0.0.1 - - [09/Dec/2024 19:46:21] "GET /dashboard HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
2024-12-09 19:46:21,422 INFO: 127.0.0.1 - - [09/Dec/2024 19:46:21] "GET /api/stats HTTP/1.1" 200 - [in /Users/lq991027/urban_lab_project/venv/lib/python3.9/site-packages/werkzeug/_internal.py:97]
